- src/addresses.ts
- src/index.ts
adding isTestnet method in PolymathAPI
> istestnet method

- babelrc.js
- package.json
- tsconfig.json
- webpack.config.js
- remove babel config since it is not being used
- add proper output configuration on webpack
- correct some details tsconfig
- add proper namespaced package name to package.json
Note: I removed some typefiles being included in the tsconfig.json file, those shouldn't be required, but keep this in mind in case something with typing does fail.
> fix: production builds

- src/PolymathAPI.ts
- yarn.lock
Added optional defaultGasPrice to API constructor
> Default gas price option

- src/index.ts
- src/types.ts
> Exported EventTypes and EventArgs

- src/PolymathAPI.ts
- src/contract_wrappers/poly_token_wrapper.ts
- src/contract_wrappers/security_token_registry_wrapper.ts
- src/contract_wrappers/security_token_wrapper.ts
- src/factories/SecurityTokenWrapperFactory.ts
Adds a factory to get ST instances by its address or ticker. 
This way, there is no need to make a 'new' statement to use them.
> SecurityTokenFactory added to PolymathAPI

- src/contract_wrappers/security_token_registry_wrapper.ts
- src/types.ts
Logs are typed automatically from the given event name for Subscribe and GetPastLogs methods.
TODO:
Make these changes on all other wrappers too.
> [WIP] Automatically typed logs 

- src/PolymathAPI.ts
- src/contract_wrappers/detailed_erc20_wrapper.ts
- src/contract_wrappers/security_token_registry_wrapper.ts
- src/factories/tokenWrapperFactory.ts
ERC20 tokens wrappers can be obtained by their address.
> ERC20 from TokenFactory

- src/contract_wrappers/contract_wrapper.ts
- src/contract_wrappers/modules/checkpoint/erc20_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/module_factory_wrapper.ts
- src/contract_wrappers/modules/module_wrapper.ts
- src/contract_wrappers/modules/permission_manager/general_permission_manager_wrapper.ts
- src/contract_wrappers/modules/sto/capped_sto_factory_wrapper.ts
- src/contract_wrappers/modules/sto/capped_sto_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_factory_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/registries/feature_registry_wrapper.ts
- src/contract_wrappers/registries/module_registry_wrapper.ts
- src/contract_wrappers/registries/polymath_registry_wrapper.ts
- src/contract_wrappers/registries/security_token_registry_wrapper.ts
- src/contract_wrappers/tokens/detailed_erc20_wrapper.ts
- src/contract_wrappers/tokens/poly_token_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
- src/types.ts
Logs related methods are moved to contract_wrapper.ts to ensure they are present in every contract wrapper.
> Abstract wrapper improvements

- src/contract_wrappers/modules/checkpoint/dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/checkpoint/erc20_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/module_wrapper.ts
- src/contract_wrappers/modules/permission_manager/general_permission_manager_wrapper.ts
- src/contract_wrappers/modules/sto/capped_sto_wrapper.ts
- src/contract_wrappers/modules/sto/sto_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/registries/feature_registry_wrapper.ts
- src/contract_wrappers/registries/module_registry_wrapper.ts
- src/contract_wrappers/registries/polymath_registry_wrapper.ts
- src/contract_wrappers/registries/security_token_registry_wrapper.ts
- src/contract_wrappers/tokens/erc20_wrapper.ts
- src/contract_wrappers/tokens/poly_token_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
Closures are not necessary any more so they are removed from each sendTransaction method.
> Remove closures

- src/contract_wrappers/modules/sto/capped_sto_wrapper.ts
- src/contract_wrappers/modules/sto/sto_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/count_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/manual_approval_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/volume_restriction_transfer_manager_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
- src/types.ts
- src/utils/convert.ts
Adding the rest of necessary human types to project
> Sto tm human types

- src/contract_wrappers/registries/__tests__/feature_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/module_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/polymath_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/security_token_registry_wrapper.test.ts
- src/contract_wrappers/registries/module_registry_wrapper.ts
- src/contract_wrappers/registries/security_token_registry_wrapper.ts
- src/utils/convert.ts
- test_utils/mocked_methods.ts
Fixed errors in tests.
Fixed bugs and typos.
> Date conversion tests

- src/PolymathAPI.ts
- src/contract_wrappers/modules/checkpoint/dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/checkpoint/erc20_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/checkpoint/ether_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/module_factory_wrapper.ts
- src/contract_wrappers/modules/module_wrapper.ts
- src/contract_wrappers/modules/permission_manager/general_permission_manager_wrapper.ts
- src/contract_wrappers/modules/sto/capped_sto_factory_wrapper.ts
- src/contract_wrappers/modules/sto/capped_sto_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_factory_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/count_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/manual_approval_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/percentage_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/volume_restriction_transfer_manager_wrapper.ts
- src/contract_wrappers/registries/__tests__/module_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/polymath_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/security_token_registry_wrapper.test.ts
- src/contract_wrappers/registries/feature_registry_wrapper.ts
- src/contract_wrappers/registries/module_registry_wrapper.ts
- src/contract_wrappers/registries/polymath_registry_wrapper.ts
- src/contract_wrappers/registries/security_token_registry_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
- src/factories/contractFactory.ts
- src/factories/moduleWrapperFactory.ts
- src/factories/tokenWrapperFactory.ts
- src/types.ts
Multiple contracts in a single wrapper feature.
ModuleName enum.
Removed lodash where it wasn't needed.
> Multiple contracts

- src/contract_wrappers/registries/__tests__/feature_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/module_registry_wrapper.test.ts
- src/contract_wrappers/registries/__tests__/security_token_registry_wrapper.test.ts
- src/contract_wrappers/registries/feature_registry_wrapper.ts
- src/contract_wrappers/registries/module_registry_wrapper.ts
- src/contract_wrappers/tokens/erc20_wrapper.ts
- src/contract_wrappers/tokens/poly_token_faucet_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
- src/utils/assert.ts
For checking the module and feature registry changes
> Registry asserts

- src/contract_wrappers/modules/permission_manager/general_permission_manager_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/count_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/manual_approval_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/percentage_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/volume_restriction_transfer_manager_wrapper.ts
- src/contract_wrappers/tokens/poly_token_faucet_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
- src/types.ts
- src/utils/assert.ts
Permission changes and asserts
> Transfer manager asserts

- src/index.ts
This PR exposes all module wrappers
> feat: export all module classes

- package.json
- release.config.js
- yarn.lock
This PR adds pre-release autopublish configuration for the develop branch
> chore: 🤖 add develop pre-release config

- src/contract_wrappers/modules/checkpoint/__tests__/dividend_checkpoint_wrapper.test.ts
- src/contract_wrappers/modules/checkpoint/dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/checkpoint/erc20_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/checkpoint/ether_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/permission_manager/general_permission_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/manual_approval_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/percentage_transfer_manager_wrapper.ts
- src/types.ts
* only operator and admin perms
* add missing perms and test verifications
> fix: refactor perms across project

- src/contract_wrappers/tokens/__tests__/alternative_erc20_wrapper.test.ts
- src/contract_wrappers/tokens/__tests__/erc20_detailed_wrapper.test.ts
- src/contract_wrappers/tokens/__tests__/erc20_wrapper.test.ts
- src/contract_wrappers/tokens/alternative_erc20_wrapper.ts
- src/contract_wrappers/tokens/erc20_detailed_wrapper.ts
These are changes for adding the alternativeerc20 token back in. Also, there was fixes made so all the tests run within these 3 erc20 wrapper files
> Alternative erc20

- examples/cappedSTO.ts
- examples/erc20Dividend.ts
- examples/etherDividend.ts
- examples/usdTieredSTO.ts
- src/contract_wrappers/modules/checkpoint/__tests__/erc20_dividend_checkpoint_wrapper.test.ts
- src/contract_wrappers/modules/checkpoint/dividend_checkpoint_wrapper.ts
Dividends checkpoints and 2 sto examples fixed
> Dividends and STO examples 3.0

- package.json
- yarn.lock
the previous version didn't decode logs properly
> fix: 🐛 use abi wrappers version with fixed decoding

- src/utils/filter_utils.ts
this was causing a bug when calling subscribeAsync
> fix: 🐛 import ethereumjs-utils correctly

- package.json
- yarn.lock
update abi wrappers version to fix log decoding
> Update abi wrappers version to fix log decoding

- src/PolymathAPI.ts
- src/factories/contractFactory.ts
All logs are decoded, even if they were emitted by another contract
> Decode all events

- src/contract_wrappers/contract_wrapper.ts
- src/contract_wrappers/modules/checkpoint/erc20_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/checkpoint/ether_dividend_checkpoint_wrapper.ts
- src/contract_wrappers/modules/module_factory_wrapper.ts
- src/contract_wrappers/modules/permission_manager/general_permission_manager_wrapper.ts
- src/contract_wrappers/modules/sto/capped_sto_wrapper.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/count_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/general_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/manual_approval_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/percentage_transfer_manager_wrapper.ts
- src/contract_wrappers/modules/transfer_manager/volume_restriction_transfer_manager_wrapper.ts
- src/contract_wrappers/registries/feature_registry_wrapper.ts
- src/contract_wrappers/registries/module_registry_wrapper.ts
- src/contract_wrappers/registries/polymath_registry_wrapper.ts
- src/contract_wrappers/registries/security_token_registry_wrapper.ts
- src/contract_wrappers/tokens/alternative_erc20_wrapper.ts
- src/contract_wrappers/tokens/erc20_detailed_wrapper.ts
- src/contract_wrappers/tokens/poly_token_wrapper.ts
- src/contract_wrappers/tokens/security_token_wrapper.ts
- src/types.ts
- yarn.lock
blockRange and indexFilterValues params are optionals
> getLogsAsync refactor

- src/contract_wrappers/modules/transfer_manager/__tests__/lock_up_transfer_manager_wrapper.test.ts
- src/contract_wrappers/modules/transfer_manager/lock_up_transfer_manager_wrapper.ts
> refactor: 💡 lockupTM period/frequency seconds in number not BN

- package.json
- release.config.js
- yarn.lock
> chore: 🤖 Added changelog plugin to semantic-release

- examples/erc20Dividend.ts
- examples/etherDividend.ts
- examples/generalPermissionManager.ts
- examples/issueTokenToInvestor.ts
- examples/usdTieredSTO.ts
- examples/vestingEscrowWallet.ts
- src/contract_wrappers/modules/sto/usd_tiered_sto_wrapper/common.ts
- src/contract_wrappers/modules/wallet/vesting_escrow_wallet_wrapper/__tests__/common.test.ts
- src/contract_wrappers/modules/wallet/vesting_escrow_wallet_wrapper/common.ts
- src/contract_wrappers/tokens/security_token_wrapper/__tests__/common.test.ts
- src/contract_wrappers/tokens/security_token_wrapper/common.ts
- src/utils/convert.ts
Covering the last of the examples that are not modular, yet.
> Final modular examples

- examples/dynamicWhitelisting.ts
- src/contract_wrappers/tokens/security_token_wrapper/__tests__/common.test.ts
- src/contract_wrappers/tokens/security_token_wrapper/common.ts
- src/contract_wrappers/tokens/security_token_wrapper/index.ts
- src/utils/sign_utils.ts
Provide a method to sign transfer data for dynamic whitelisting
purposes. Also added validations for data args con those methods which
corresponds
BREAKING CHANGE: data arg must be hex string when required
> feat: 🎸 Add sign transfer data method for dynamic whitelisting
